-- Day 26: Capstone Project - Banking Transaction Schema
-- Concept: Designing a robust transaction schema with audit capabilities

CREATE TABLE accounts (
    account_number VARCHAR2(20 CHAR) PRIMARY KEY,
    customer_name VARCHAR2(100 CHAR) NOT NULL,
    account_type VARCHAR2(10 CHAR) CHECK (account_type IN ('SAVINGS', 'CHECKING')),
    balance NUMBER(15,2) DEFAULT 0.00 NOT NULL,
    status VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    last_updated TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR2(20 CHAR) REFERENCES accounts(account_number),
    transaction_type VARCHAR2(15 CHAR) CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_IN', 'TRANSFER_OUT')),
    amount NUMBER(15,2) CHECK (amount > 0),
    transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    description VARCHAR2(200 CHAR)
);

CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR2(20 CHAR),
    old_balance NUMBER(15,2),
    new_balance NUMBER(15,2),
    changed_by VARCHAR2(50 CHAR),
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
