-- Day 9: E-Commerce Analytics Database Setup
-- Concept: Relational integrity across multi-table transactional architectures

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50 CHAR) NOT NULL,
    last_name VARCHAR2(50 CHAR) NOT NULL,
    email VARCHAR2(100 CHAR) UNIQUE,
    country VARCHAR2(50 CHAR),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100 CHAR) NOT NULL,
    category VARCHAR2(50 CHAR),
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES customers(customer_id),
    order_date DATE DEFAULT SYSDATE NOT NULL,
    status VARCHAR2(20 CHAR) CHECK (status IN ('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    total_amount NUMBER(12,2)
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES orders(order_id),
    product_id NUMBER REFERENCES products(product_id),
    quantity NUMBER NOT NULL,
    unit_price NUMBER(10,2) NOT NULL
);

INSERT INTO customers (first_name, last_name, email, country) VALUES ('Alice', 'Smith', 'alice@email.com', 'USA');
INSERT INTO customers (first_name, last_name, email, country) VALUES ('Bob', 'Jones', 'bob@email.com', 'UK');
INSERT INTO customers (first_name, last_name, email, country) VALUES ('Charlie', 'Brown', 'charlie@email.com', 'Canada');

INSERT INTO products (product_name, category, price, stock_quantity) VALUES ('Laptop Pro', 'Electronics', 1200.00, 15);
INSERT INTO products (product_name, category, price, stock_quantity) VALUES ('Wireless Mouse', 'Electronics', 25.00, 100);
INSERT INTO products (product_name, category, price, stock_quantity) VALUES ('Mechanical Keyboard', 'Electronics', 80.00, 45);
INSERT INTO products (product_name, category, price, stock_quantity) VALUES ('Coffee Mug', 'Home', 15.00, 200);

INSERT INTO orders (customer_id, order_date, status, total_amount) VALUES (1, SYSDATE - 10, 'DELIVERED', 1225.00);
INSERT INTO orders (customer_id, order_date, status, total_amount) VALUES (2, SYSDATE - 5, 'SHIPPED', 105.00);
INSERT INTO orders (customer_id, order_date, status, total_amount) VALUES (1, SYSDATE - 2, 'PENDING', 80.00);

INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (1, 1, 1, 1200.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (1, 2, 1, 25.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (2, 2, 1, 25.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (2, 3, 1, 80.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (3, 3, 1, 80.00);
COMMIT;
