-- Day 1: Employee Management Database - Schema Setup
-- Concept: Data Definition Language (DDL) and Oracle Tables
-- DDL statements are used to define the database structure, such as tables, views, and indexes.
-- Oracle tables store data in rows and columns.
-- CONCEPT - GENERATED BY DEFAULT AS IDENTITY:
--   Introduced in Oracle 12c, this automatically assigns a unique, sequential number 
--   to the primary key if no value is explicitly provided. It is backed by a system-generated sequence.

CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(50 CHAR) NOT NULL,
    location VARCHAR2(100 CHAR)
);

CREATE TABLE jobs (
    job_id VARCHAR2(10) PRIMARY KEY,
    job_title VARCHAR2(50 CHAR) NOT NULL,
    min_salary NUMBER(8,2),
    max_salary NUMBER(8,2)
);

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50 CHAR),
    last_name VARCHAR2(50 CHAR) NOT NULL,
    email VARCHAR2(100 CHAR),
    phone_number VARCHAR2(20 CHAR),
    hire_date DATE DEFAULT SYSDATE NOT NULL,
    job_id VARCHAR2(10),
    salary NUMBER(8,2),
    commission_pct NUMBER(2,2),
    manager_id NUMBER,
    department_id NUMBER
);
